name: deploy to server

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
        run: |
          scp -o StrictHostKeyChecking=no -r ./ ${{ secrets.SSH_NAME }}@${{ secrets.SSH_HOST }}:/home/deployer/Simple_Blog
  
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_NAME }}@${{ secrets.SSH_HOST }} << EOF
              cd /home/deployer/Simple_Blog
              docker-compose down
              git pull
              docker-compose up --build
            EOF
