name: deploy to server

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5


    - name: ssh key
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: update
      run: |
        ssh -o StrictHostKeyChecking=no -tt ${{ secrets.SSH_NAME }}@${{ secrets.SSH_HOST }} << EOF
          cd /home/deployer/Simple_Blog
          docker-compose down
          git pull
          docker-compose up --build
        EOF
