name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SSH/SCP Pipeline
        with:
          run: | 
            apt-get update && apt install -y openssh
            ssh $SSH_USER@SSH_HOST
            $SSH_PASS
            mkdir test
            exit
            |
