name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SSH/SCP Pipeline
        uses: kangketikonlen/ssh-pipeline@v0.0.3 # Use your action's repo and version
        with:
          # --- Connection Details (from Secrets) ---
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_NAME }}
          key: ${{ secrets.SSH_PASS }}

          # --- Pipeline Commands ---
          first_ssh: |
            echo "Starting deployment..."
            echo "Connected from a GitHub Actions runner!"

          scp: |
            # Copy build artifacts or other files
            # Format: 'local/path => remote/path'
            README.md => /tmp/

          last_ssh: |
            echo "File transfer complete."
            echo "Verifying file on remote server:"
            ls -l /tmp/README.md
